---
- name: Install and configure Nginx
  hosts: test_hosts
  become: yes

  vars:
    src_file: ./site/index.html
    dest_file: /var/www/html

  tasks:
  - name: Install Nginx
    package:
      name: nginx
      state: latest

  - name: Configure Nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Copy index.html to server
    copy:
      src: "{{ src_file }}"
      dest: "{{ dest_file }}"
      mode: 0555
    notify:
      - Restart NGINX
    
    - name: Check service started
      systemd_service:
        state: started
        name: nginx


  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted 

