---
- name: Delete NGINX and Apache on Debian servers
  hosts: test_hosts
  become: yes

  tasks:
  - name: Stop Apache2 services
    ansible.builtin.service:
      name: apache2
      state: stopped
    ignore_errors: true

  - name: Stop NGINX services
    ansible.builtin.service:
      name: nginx
      state: stopped
    ignore_errors: true

  - name: Delete Apache2
    ansible.builtin.apt:
      name: apache2
      state: absent
      purge: true

  - name: Delete NGINX
    ansible.builtin.apt:
      name: nginx
      state: absent
      purge: true
