---
# tasks file for deploy_apache_web

- block: #===========BLOCK FOR DEBIAN==============
    - name: Install Apache on Debian
      package: name=apache2 state=latest

    - name: Start Apache on Debian
      service: name=apache2 state=started enabled=yes

  when: ansible_os_family == "Debian"    

- block: #===========BLOCK FOR REDHAT==============
    - name: Install Apache on RedHat
      package: name=httpd state=latest

    - name: Start Apache on RedHat
      service: name=httpd state=started enabled=yes
  
  when: ansible_os_family == "RedHat"

- name: Copy index.html to server
  copy: 
    src: index.html 
    dest: "{{ dest_file }}"
  notify:
    - Restart Apache Debian
    - Restart Apache RedHat 
